'use strict';
let briefingData=null;let activeCategory='All';
const elements={briefingDate:document.getElementById('briefing-date'),briefingStatus:document.getElementById('briefing-status'),executiveSummary:document.getElementById('executive-summary'),storyCount:document.getElementById('story-count'),sourceCount:document.getElementById('source-count'),countryCount:document.getElementById('country-count'),categoryCount:document.getElementById('category-count'),searchInput:document.getElementById('search-input'),countryFilter:document.getElementById('country-filter'),categoryButtons:document.getElementById('category-buttons'),storyList:document.getElementById('story-list'),resultsSummary:document.getElementById('results-summary'),refreshButton:document.getElementById('refresh-button'),themeToggle:document.getElementById('theme-toggle'),learningType:document.getElementById('learning-type'),learningHeading:document.getElementById('learning-heading'),learningDescription:document.getElementById('learning-description'),methodologyText:document.getElementById('methodology-text')};
async function loadBriefing(){setStatus('Loading today’s briefing');try{const response=await fetch(`briefing.json?${Date.now()}`,{cache:'no-store'});if(!response.ok)throw new Error(`Could not load briefing.json (${response.status})`);briefingData=await response.json();initialiseDashboard();setStatus('Briefing loaded','success')}catch(error){console.error(error);setStatus('Briefing failed to load','error');showLoadError(error)}}
function initialiseDashboard(){updateHeader();updateExecutiveSummary();updateStatistics();populateCountryDropdown();renderLearningCard();renderMethodology();renderStories()}
function updateHeader(){const value=briefingData?.date||briefingData?.generated_at;if(!value){elements.briefingDate.textContent='Date unavailable';return}const date=new Date(value);elements.briefingDate.textContent=Number.isNaN(date.getTime())?String(value):new Intl.DateTimeFormat('en-GB',{day:'numeric',month:'long',year:'numeric'}).format(date)}
function updateExecutiveSummary(){elements.executiveSummary.textContent=briefingData?.executive_summary||'No executive summary is available for this briefing.'}
function getStories(){return Array.isArray(briefingData?.stories)?briefingData.stories:[]}
function updateStatistics(){const stories=getStories(),stats=briefingData?.statistics||{};elements.storyCount.textContent=stats.story_count??stories.length;elements.sourceCount.textContent=stats.source_count??new Set(stories.map(s=>s.source).filter(Boolean)).size;elements.countryCount.textContent=stats.country_count??new Set(stories.map(s=>s.country).filter(c=>c&&c!=='Regional')).size;elements.categoryCount.textContent=stats.category_count??new Set(stories.map(s=>s.category).filter(Boolean)).size}
function populateCountryDropdown(){const countries=[...new Set(getStories().map(s=>s.country).filter(Boolean))].sort((a,b)=>a.localeCompare(b));elements.countryFilter.innerHTML='<option value="All">All countries</option>';countries.forEach(country=>{const option=document.createElement('option');option.value=country;option.textContent=country;elements.countryFilter.appendChild(option)})}
function renderLearningCard(){const l=briefingData?.learning;if(!l){elements.learningType.textContent='Daily learning point';elements.learningHeading.textContent='Learning point unavailable';elements.learningDescription.textContent='No learning point was included in today’s briefing.';return}elements.learningType.textContent=l.type||'Daily learning point';elements.learningHeading.textContent=l.title||'West Africa learning point';elements.learningDescription.textContent=l.description||'No description is available.'}
function renderMethodology(){if(briefingData?.methodology)elements.methodologyText.textContent=briefingData.methodology}
function getFilteredStories(){const term=elements.searchInput.value.trim().toLowerCase(),country=elements.countryFilter.value;return getStories().filter(story=>{const categoryMatch=activeCategory==='All'||story.category===activeCategory;const countryMatch=country==='All'||story.country===country;const text=[story.title,story.summary,story.source,story.country,story.category].filter(Boolean).join(' ').toLowerCase();return categoryMatch&&countryMatch&&(term===''||text.includes(term))})}
function renderStories(){const filtered=getFilteredStories(),total=getStories().length;elements.storyList.innerHTML='';elements.resultsSummary.textContent=filtered.length===total?`${total} ranked stories`:`${filtered.length} of ${total} stories shown`;if(filtered.length===0){elements.storyList.innerHTML='<div class="empty-state"><strong>No matching stories.</strong><p>Try changing the search term or filters.</p></div>';return}filtered.forEach((story,index)=>elements.storyList.appendChild(createStoryCard(story,index===0)))}
function createStoryCard(story,isFirst){const article=document.createElement('article'),category=story.category||'General',country=story.country||'Regional',source=story.source||'Unknown source',rank=story.rank??'',published=formatPublishedDate(story.published_at);article.className='story-card';if(isFirst)article.classList.add('featured');if(category==='Security')article.classList.add('security');article.innerHTML=`<div class="story-topline"><span class="story-rank">${rank||'•'}</span><span class="badge category-badge ${category==='Security'?'category-security':''}">${escapeHtml(category)}</span><span class="badge country-badge">${escapeHtml(country)}</span></div><h3>${escapeHtml(story.title||'Untitled story')}</h3><p class="story-summary">${escapeHtml(story.summary||'No summary is available for this story.')}</p><div class="story-footer"><div class="story-meta"><span>${escapeHtml(source)}</span>${published?`<span>•</span><span>${escapeHtml(published)}</span>`:''}</div>${story.url?`<a class="read-source" href="${escapeAttribute(story.url)}" target="_blank" rel="noopener noreferrer">Read source →</a>`:''}</div>`;return article}
function formatPublishedDate(value){if(!value)return'';const date=new Date(value);if(Number.isNaN(date.getTime()))return'';const hours=Math.floor((Date.now()-date.getTime())/3600000),days=Math.floor(hours/24);if(hours>=0&&hours<1)return'Less than 1 hour ago';if(hours>=1&&hours<24)return`${hours} hour${hours===1?'':'s'} ago`;if(days>=1&&days<7)return`${days} day${days===1?'':'s'} ago`;return new Intl.DateTimeFormat('en-GB',{day:'numeric',month:'short',year:'numeric'}).format(date)}
function setStatus(message,type=''){elements.briefingStatus.textContent=message;elements.briefingStatus.classList.remove('success','error');if(type)elements.briefingStatus.classList.add(type)}
function showLoadError(error){elements.executiveSummary.textContent='The briefing could not be loaded. Make sure the local server is running and briefing.json is in the same folder as index.html.';elements.storyList.innerHTML=`<div class="error-card"><strong>Unable to load briefing.</strong><p>${escapeHtml(error.message||String(error))}</p></div>`;elements.resultsSummary.textContent=''}
function escapeHtml(value){return String(value).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;')}
function escapeAttribute(value){return escapeHtml(value)}
function restoreTheme(){if(localStorage.getItem('wa-intelligence-theme')==='dark')document.body.classList.add('dark-mode');updateThemeButtonLabel()}
function toggleTheme(){document.body.classList.toggle('dark-mode');localStorage.setItem('wa-intelligence-theme',document.body.classList.contains('dark-mode')?'dark':'light');updateThemeButtonLabel()}
function updateThemeButtonLabel(){elements.themeToggle.textContent=document.body.classList.contains('dark-mode')?'Light mode':'Dark mode'}
elements.searchInput.addEventListener('input',renderStories);elements.countryFilter.addEventListener('change',renderStories);elements.categoryButtons.addEventListener('click',event=>{const button=event.target.closest('[data-category]');if(!button)return;activeCategory=button.dataset.category;elements.categoryButtons.querySelectorAll('[data-category]').forEach(b=>b.classList.toggle('active',b===button));renderStories()});elements.refreshButton.addEventListener('click',loadBriefing);elements.themeToggle.addEventListener('click',toggleTheme);restoreTheme();loadBriefing();
