{
  "date":"2026-07-22","display_date":"Demonstration edition — replace by running the updater","is_demo":true,"sources_scanned":0,"dominant_theme":"Politics","topic_mix":{"Politics":3,"Economy":2,"Security":2,"Society":2,"Climate":1},
  "country_signals":[
    {"country":"Nigeria","score":82,"label":"High attention","reason":"Demonstration reporting signal"},{"country":"Mali","score":74,"label":"Active","reason":"Demonstration reporting signal"},{"country":"Ghana","score":66,"label":"Active","reason":"Demonstration reporting signal"},{"country":"Senegal","score":58,"label":"Monitored","reason":"Demonstration reporting signal"},{"country":"Niger","score":55,"label":"Monitored","reason":"Demonstration reporting signal"},{"country":"Côte d’Ivoire","score":48,"label":"Monitored","reason":"Demonstration reporting signal"},{"country":"Guinea","score":44,"label":"Monitored","reason":"Demonstration reporting signal"},{"country":"Regional","score":40,"label":"Regional","reason":"Cross-border themes"}],
  "analysis":{"title":"This is a functioning demonstration","summary":"These are illustrative placeholders, not current news. Running the GitHub Action replaces them with source-linked reporting gathered that day.","watch":["Confirm the scheduled workflow has permission to write to the repository.","Open original reports before treating developing claims as established.","Add an OpenAI API secret only when you want enhanced analytical summaries."]},
  "study_prompt":{"question":"Which regional institution could shape these developments?","context":"Use this demonstration to test filters and layout, then run the updater for a live edition."},
  "items":[
    {"headline":"Live daily reporting will replace this demonstration","summary":"The app is displaying correctly. Run the Update Daily Brief workflow in GitHub Actions to gather current reports and generate a fresh edition.","why_it_matters":"This confirms the website can load its briefing data before automation is configured.","category":"Politics","country":"Regional","source":"Setup guide","published":"Demonstration","url":"https://docs.github.com/actions","confidence":"Illustrative only"},
    {"headline":"Political developments are ranked by regional significance","summary":"The updater searches country and regional queries, then scores recent developments and reduces duplicate coverage.","why_it_matters":"Ranking helps focus limited reading time on events with likely regional consequences.","category":"Politics","country":"Nigeria","source":"App methodology","published":"Demonstration","url":"https://news.google.com/","confidence":"Illustrative only"},
    {"headline":"Economic stories include debt, currencies and investment","summary":"Business and macroeconomic reporting is categorised alongside political and security news rather than being separated from the daily picture.","why_it_matters":"Economic pressure often shapes government stability and policy choices.","category":"Economy","country":"Ghana","source":"App methodology","published":"Demonstration","url":"https://news.google.com/","confidence":"Illustrative only"},
    {"headline":"Security coverage is balanced against duplicate reporting","summary":"Similar headlines are removed and publisher limits reduce the chance that one heavily covered incident overwhelms the briefing.","why_it_matters":"News volume is not the same as strategic importance.","category":"Security","country":"Mali","source":"Code Sentinel","published":"Demonstration","url":"https://news.google.com/","confidence":"Illustrative only"},
    {"headline":"ECOWAS and cross-border effects remain visible","summary":"Regional searches capture developments involving diplomacy, sanctions, trade, migration and shared security challenges.","why_it_matters":"National developments frequently create spillovers across neighbouring states.","category":"Politics","country":"Senegal","source":"App methodology","published":"Demonstration","url":"https://www.ecowas.int/","confidence":"Illustrative only"},
    {"headline":"Social policy receives space beside elite politics","summary":"Health, education, protests, rights and migration can be selected when the reporting is judged consequential.","why_it_matters":"Political risk includes social pressures that may not appear in conventional market headlines.","category":"Society","country":"Guinea","source":"App methodology","published":"Demonstration","url":"https://news.google.com/","confidence":"Illustrative only"},
    {"headline":"Climate shocks are treated as political-risk factors","summary":"Flooding, drought, rainfall, energy and environmental developments are included in the topic model.","why_it_matters":"Climate events can affect food prices, displacement and public confidence.","category":"Climate","country":"Niger","source":"App methodology","published":"Demonstration","url":"https://news.google.com/","confidence":"Illustrative only"},
    {"headline":"Country scores describe attention rather than probability","summary":"The dashboard converts selected story volume into a simple attention score and explicitly avoids presenting it as a forecast.","why_it_matters":"False precision can mislead readers about complex political outcomes.","category":"Security","country":"Côte d’Ivoire","source":"Code Sentinel","published":"Demonstration","url":"https://news.google.com/","confidence":"Illustrative only"},
    {"headline":"Every selected item keeps its original source link","summary":"Publisher names, timestamps and links remain visible so the reader can inspect the evidence behind each summary.","why_it_matters":"Traceability is essential when automated summaries cover contested or developing events.","category":"Society","country":"Liberia","source":"Code Sentinel","published":"Demonstration","url":"https://news.google.com/","confidence":"Illustrative only"},
    {"headline":"An archive preserves successful daily editions","summary":"Each completed run stores a dated copy of the briefing in the data archive while updating the current dashboard.","why_it_matters":"Historical editions make it easier to identify recurring themes and changes over time.","category":"Economy","country":"Regional","source":"App feature","published":"Demonstration","url":"https://docs.github.com/pages","confidence":"Illustrative only"}
  ]
}
